FROM python:3.12-slim@sha256:2fe5997d249a808b8eeea52c58a1dbffbba28754dc11699ef5c029f2d818ce79
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
COPY . /app
USER 1000:1000
RUN python -m unittest discover -s tests -v && python ci/check_repository.py
HEALTHCHECK NONE
CMD ["python", "ci/check_repository.py"]
